create table person_data
(
    birth_date date         not null,
    id         bigint generated by default as identity
        primary key,
    sex        varchar(10)
        constraint person_data_sex_check
            check ((sex)::text = ANY
        ((ARRAY ['MALE'::character varying, 'FEMALE'::character varying, 'UNKNOWN'::character varying])::text[])),
    phone      varchar(20)  not null
        unique,
    full_name  varchar(80)  not null,
    email      varchar(100) not null
        unique
);

alter table person_data
    owner to postgres;

create table candidates
(
    expected_salary integer,
    experience      integer,
    created_at      timestamp(6),
    id              bigint generated by default as identity
        primary key,
    person_data_id  bigint
        unique
        constraint fkbntelyh5y12kbqlm5ajfgdo6p
            references person_data
            on delete cascade,
    resume_url      varchar(255),
    skills          text
);

alter table candidates
    owner to postgres;

create table sources
(
    id   bigint generated by default as identity
        primary key,
    name varchar(50) not null
        unique
);

alter table sources
    owner to postgres;

create table users
(
    is_blocked     boolean      not null,
    id             bigint generated by default as identity
        primary key,
    person_data_id bigint
        unique
        constraint fk89cgxw185b3qd4oibj3vh67cp
            references person_data
            on delete cascade,
    role           varchar(20)  not null
        constraint users_role_check
            check ((role)::text = ANY
        ((ARRAY ['ADMIN'::character varying, 'HR_MANAGER'::character varying, 'CANDIDATE'::character varying])::text[])),
    username       varchar(50)  not null
        unique,
    password_hash  varchar(255) not null
);

alter table users
    owner to postgres;

create table departments
(
    id         bigint generated by default as identity
        primary key,
    manager_id bigint
        constraint fkia71ute4clfbt6u2auufvw1bv
            references users
            on delete set null,
    name       varchar(100) not null
        unique
);

alter table departments
    owner to postgres;

create table vacancies
(
    salary_max    integer,
    salary_min    integer,
    closed_at     timestamp(6),
    created_at    timestamp(6),
    department_id bigint
        constraint fkj7m4kkf07vg8og788pemj7fs7
            references departments
            on delete cascade,
    hr_manager_id bigint
        constraint fkkkdhydpa3rfjq9x8neatxkrrl
            references users
            on delete set null,
    id            bigint generated by default as identity
        primary key,
    status        varchar(20)  not null
        constraint vacancies_status_check
            check ((status)::text = ANY
        ((ARRAY ['OPEN'::character varying, 'CLOSED'::character varying, 'ON_HOLD'::character varying])::text[])),
    work_format   varchar(20)  not null
        constraint vacancies_work_format_check
            check ((work_format)::text = ANY
                   ((ARRAY ['OFFICE'::character varying, 'REMOTE'::character varying, 'HYBRID'::character varying])::text[])),
    title         varchar(100) not null,
    description   text,
    requirements  text
);

alter table vacancies
    owner to postgres;

create table applications
(
    applied_at   timestamp(6),
    candidate_id bigint
        constraint fkg4e16cwk1qrad923bpx4hamdh
            references candidates
            on delete cascade,
    id           bigint generated by default as identity
        primary key,
    source_id    bigint
        constraint fkhr86swxmgukewljhoidi69g7b
            references sources
            on delete set null,
    updated_at   timestamp(6),
    vacancy_id   bigint
        constraint fkq2axowr8ewvl0ncquhtq8od8j
            references vacancies
            on delete cascade,
    status       varchar(30)
        constraint applications_status_check
            check ((status)::text = ANY
        ((ARRAY ['NEW'::character varying, 'REVIEWED'::character varying, 'INTERVIEW_SCHEDULED'::character varying, 'REJECTED'::character varying, 'OFFERED'::character varying, 'HIRED'::character varying, 'RESERVE'::character varying])::text[])),
    offer_text   text
);

alter table applications
    owner to postgres;

create table interviews
(
    application_id bigint
        constraint fkok2bail5ls3jjbjgl5c6nt620
            references applications
            on delete cascade,
    id             bigint generated by default as identity
        primary key,
    scheduled_date timestamp(6) not null,
    status         varchar(20)  not null
        constraint interviews_status_check
            check ((status)::text = ANY
        ((ARRAY ['SCHEDULED'::character varying, 'COMPLETED'::character varying, 'CANCELED'::character varying])::text[])),
    location       varchar(255) not null
);

alter table interviews
    owner to postgres;

create table evaluations
(
    is_passed    boolean,
    score        integer,
    evaluated_at timestamp(6),
    evaluator_id bigint
        constraint fkqihdmjba0yaamhjp8gr00c27m
            references users
            on delete set null,
    id           bigint generated by default as identity
        primary key,
    interview_id bigint
        unique
        constraint fkp13r4xxbckdnor6gqmw6g4jnp
            references interviews
            on delete cascade,
    comments     text
);

alter table evaluations
    owner to postgres;

