package org.kurilin.recruitment.shared.enums;

public enum RequestType {
    LOGIN,

    // Candidate
    REGISTER_CANDIDATE,
    UPDATE_PROFILE,
    SEARCH_VACANCIES,
    APPLY_FOR_VACANCY,
    CHANGE_PASSWORD,
    GET_ALL_SOURCES,
    GET_MY_APPLICATIONS,
    GET_CANDIDATE_PROFILE,

    // HR
    SEARCH_CANDIDATES,
    GET_OPEN_VACANCIES,
    UPDATE_APPLICATION_STATUS,
    CALCULATE_SCORING,
    SCHEDULE_INTERVIEW,
    AGGREGATE_EVALUATIONS,
    GENERATE_REPORT_FUNNEL,
    GENERATE_REPORT_SOURCES,
    GENERATE_REPORT_TIME,
    GENERATE_OFFER,
    GET_VACANCY_APPLICATIONS,
    GET_HR_INTERVIEWS,
    ADD_EVALUATION,
    GET_ALL_DEPARTMENTS,
    GET_EVALUATION,


    // Admin
    ADD_USER,
    UPDATE_USER,
    BLOCK_USER,
    DELETE_USER,
    GET_ALL_USERS,

    // Vacancy
    CREATE_VACANCY,
    UPDATE_VACANCY,
    CLOSE_VACANCY
}
